#
#---------------------------FRONTEND------------------------------------------
#


#
#---------------------------CATALOGUE------------------------------------------
#

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalogue
  namespace: roboshop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: catalogue


---

#
#---------------------------MONGODB------------------------------------------
#


#
#---------------------------USER------------------------------------------
#


#
#---------------------------CART------------------------------------------
#


#
#---------------------------SHIPPING------------------------------------------
#


#
#---------------------------SHIPPING_DB------------------------------------------
#


#
#---------------------------PAYMENT------------------------------------------
#