#
#---------------------------FRONTEND------------------------------------------
#


#
#---------------------------CATALOGUE------------------------------------------
#

---

apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen-catalogue
  namespace: roboshop
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wrk
          image: curlimages/curl:8.8.0
          command: ["/bin/sh","-c"]
          args:
            - |
              for i in $(seq 1 100000); do
                curl -s http://catalogue.roboshop.svc.cluster.local:8080/health > /dev/null || true
              done


---

#
#---------------------------MONGODB------------------------------------------
#


#
#---------------------------USER------------------------------------------
#


#
#---------------------------CART------------------------------------------
#


#
#---------------------------SHIPPING------------------------------------------
#


#
#---------------------------SHIPPING_DB------------------------------------------
#


#
#---------------------------PAYMENT------------------------------------------
#