name: testing minikube

on: [push,workflow_dispatch]


jobs:
  testing-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Start Minikube (action)
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: '1.34.0'          # optional: pick a version
          kubernetes-version: 'v1.32.0'      # optional
          driver: 'docker'                   # docker driver runs on the runner
          container-runtime: 'containerd'    # optional
          cpus: '2'
          memory: '4096'
          addons: 'ingress,dashboard'        # optional addons to enable

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Verify cluster
        run: |
          docker --version
          kubectl version 
          kubectl get nodes -o wide